#!/bin/sh
#
# Gradle start up script for POSIX generated by "Gradle init".
#

APP_HOME=$(cd "$(dirname "$0")" && pwd)
GRADLE_USER_HOME=${GRADLE_USER_HOME:-$HOME/.gradle}
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

exec java -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
